// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/config.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	config "github.com/Pklerik/urlshortener/internal/config"
	audit "github.com/Pklerik/urlshortener/internal/config/audit"
	dbconf "github.com/Pklerik/urlshortener/internal/config/dbconf"
	gomock "github.com/golang/mock/gomock"
)

// MockStartupFlagsParser is a mock of StartupFlagsParser interface.
type MockStartupFlagsParser struct {
	ctrl     *gomock.Controller
	recorder *MockStartupFlagsParserMockRecorder
}

// MockStartupFlagsParserMockRecorder is the mock recorder for MockStartupFlagsParser.
type MockStartupFlagsParserMockRecorder struct {
	mock *MockStartupFlagsParser
}

// NewMockStartupFlagsParser creates a new mock instance.
func NewMockStartupFlagsParser(ctrl *gomock.Controller) *MockStartupFlagsParser {
	mock := &MockStartupFlagsParser{ctrl: ctrl}
	mock.recorder = &MockStartupFlagsParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStartupFlagsParser) EXPECT() *MockStartupFlagsParserMockRecorder {
	return m.recorder
}

// GetAddressShortURL mocks base method.
func (m *MockStartupFlagsParser) GetAddressShortURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddressShortURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAddressShortURL indicates an expected call of GetAddressShortURL.
func (mr *MockStartupFlagsParserMockRecorder) GetAddressShortURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddressShortURL", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetAddressShortURL))
}

// GetAudit mocks base method.
func (m *MockStartupFlagsParser) GetAudit() *audit.Audit {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAudit")
	ret0, _ := ret[0].(*audit.Audit)
	return ret0
}

// GetAudit indicates an expected call of GetAudit.
func (mr *MockStartupFlagsParserMockRecorder) GetAudit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAudit", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetAudit))
}

// GetDatabaseConf mocks base method.
func (m *MockStartupFlagsParser) GetDatabaseConf() (dbconf.DBConfigurer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabaseConf")
	ret0, _ := ret[0].(dbconf.DBConfigurer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseConf indicates an expected call of GetDatabaseConf.
func (mr *MockStartupFlagsParserMockRecorder) GetDatabaseConf() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseConf", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetDatabaseConf))
}

// GetLocalStorage mocks base method.
func (m *MockStartupFlagsParser) GetLocalStorage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalStorage")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLocalStorage indicates an expected call of GetLocalStorage.
func (mr *MockStartupFlagsParserMockRecorder) GetLocalStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalStorage", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetLocalStorage))
}

// GetLogLevel mocks base method.
func (m *MockStartupFlagsParser) GetLogLevel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogLevel")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLogLevel indicates an expected call of GetLogLevel.
func (mr *MockStartupFlagsParserMockRecorder) GetLogLevel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogLevel", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetLogLevel))
}

// GetSecretKey mocks base method.
func (m *MockStartupFlagsParser) GetSecretKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSecretKey indicates an expected call of GetSecretKey.
func (mr *MockStartupFlagsParserMockRecorder) GetSecretKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretKey", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetSecretKey))
}

// GetServerAddress mocks base method.
func (m *MockStartupFlagsParser) GetServerAddress() config.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerAddress")
	ret0, _ := ret[0].(config.Address)
	return ret0
}

// GetServerAddress indicates an expected call of GetServerAddress.
func (mr *MockStartupFlagsParserMockRecorder) GetServerAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerAddress", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetServerAddress))
}

// GetTimeout mocks base method.
func (m *MockStartupFlagsParser) GetTimeout() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeout")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetTimeout indicates an expected call of GetTimeout.
func (mr *MockStartupFlagsParserMockRecorder) GetTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeout", reflect.TypeOf((*MockStartupFlagsParser)(nil).GetTimeout))
}
