// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Pklerik/urlshortener/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockLinksRepository is a mock of LinksRepository interface.
type MockLinksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinksRepositoryMockRecorder
}

// MockLinksRepositoryMockRecorder is the mock recorder for MockLinksRepository.
type MockLinksRepositoryMockRecorder struct {
	mock *MockLinksRepository
}

// NewMockLinksRepository creates a new mock instance.
func NewMockLinksRepository(ctrl *gomock.Controller) *MockLinksRepository {
	mock := &MockLinksRepository{ctrl: ctrl}
	mock.recorder = &MockLinksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinksRepository) EXPECT() *MockLinksRepositoryMockRecorder {
	return m.recorder
}

// BatchMarkAsDeleted mocks base method.
func (m *MockLinksRepository) BatchMarkAsDeleted(ctx context.Context, links chan model.LinkData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchMarkAsDeleted", ctx, links)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchMarkAsDeleted indicates an expected call of BatchMarkAsDeleted.
func (mr *MockLinksRepositoryMockRecorder) BatchMarkAsDeleted(ctx, links interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchMarkAsDeleted", reflect.TypeOf((*MockLinksRepository)(nil).BatchMarkAsDeleted), ctx, links)
}

// CreateUser mocks base method.
func (m *MockLinksRepository) CreateUser(ctx context.Context, userID model.UserID) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userID)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockLinksRepositoryMockRecorder) CreateUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockLinksRepository)(nil).CreateUser), ctx, userID)
}

// FindShort mocks base method.
func (m *MockLinksRepository) FindShort(ctx context.Context, short string) (model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShort", ctx, short)
	ret0, _ := ret[0].(model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShort indicates an expected call of FindShort.
func (mr *MockLinksRepositoryMockRecorder) FindShort(ctx, short interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShort", reflect.TypeOf((*MockLinksRepository)(nil).FindShort), ctx, short)
}

// GetStats mocks base method.
func (m *MockLinksRepository) GetStats(ctx context.Context) (model.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(model.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockLinksRepositoryMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockLinksRepository)(nil).GetStats), ctx)
}

// PingDB mocks base method.
func (m *MockLinksRepository) PingDB(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDB", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDB indicates an expected call of PingDB.
func (mr *MockLinksRepositoryMockRecorder) PingDB(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDB", reflect.TypeOf((*MockLinksRepository)(nil).PingDB), ctx)
}

// SelectUserLinks mocks base method.
func (m *MockLinksRepository) SelectUserLinks(ctx context.Context, userID model.UserID) ([]model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserLinks", ctx, userID)
	ret0, _ := ret[0].([]model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserLinks indicates an expected call of SelectUserLinks.
func (mr *MockLinksRepositoryMockRecorder) SelectUserLinks(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserLinks", reflect.TypeOf((*MockLinksRepository)(nil).SelectUserLinks), ctx, userID)
}

// SetLinks mocks base method.
func (m *MockLinksRepository) SetLinks(ctx context.Context, links []model.LinkData) ([]model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLinks", ctx, links)
	ret0, _ := ret[0].([]model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetLinks indicates an expected call of SetLinks.
func (mr *MockLinksRepositoryMockRecorder) SetLinks(ctx, links interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLinks", reflect.TypeOf((*MockLinksRepository)(nil).SetLinks), ctx, links)
}
