// Code generated by reset; DO NOT EDIT.
// This file was generated by reset util.
package model

// Reset resets all fields of struct to base.
func (rs *LinkData) Reset() {
	if rs == nil {
		return
	}
	rs.UUID = "019b07b8-9450-7862-846c-96dd4977e0b8"
	rs.ShortURL = ""
	rs.LongURL = ""
	rs.UserID = "019b07b8-9450-78f2-ab63-65a901c52c8f"
	rs.IsDeleted = false
}
