// Code generated by reset; DO NOT EDIT.
// This file was generated by reset util.
package model

// Reset resets all fields of struct to base.
func (rs *Request) Reset() {
	if rs == nil {
		return
	}
	rs.URL = ""
}

// Reset resets all fields of struct to base.
func (rs *ReqPostBatch) Reset() {
	if rs == nil {
		return
	}
	rs.CorrelationID = ""
	rs.LongURL = ""
}
