// Code generated by reset; DO NOT EDIT.
// This file was generated by reset util.
package testfolder

// Reset resets all fields of struct to base.
func (rs *TestStr) Reset() {
	if rs == nil {
		return
	}
	rs.stringB = ""
	rs.intB = 0
	rs.floatB = 0
	rs.arrayB = rs.arrayB[:0]
	clear(rs.mapB)
}
