// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Pklerik/urlshortener/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockLinkServicer is a mock of LinkServicer interface.
type MockLinkServicer struct {
	ctrl     *gomock.Controller
	recorder *MockLinkServicerMockRecorder
}

// MockLinkServicerMockRecorder is the mock recorder for MockLinkServicer.
type MockLinkServicerMockRecorder struct {
	mock *MockLinkServicer
}

// NewMockLinkServicer creates a new mock instance.
func NewMockLinkServicer(ctrl *gomock.Controller) *MockLinkServicer {
	mock := &MockLinkServicer{ctrl: ctrl}
	mock.recorder = &MockLinkServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkServicer) EXPECT() *MockLinkServicerMockRecorder {
	return m.recorder
}

// GetSecret mocks base method.
func (m *MockLinkServicer) GetSecret(name string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecret", name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetSecret indicates an expected call of GetSecret.
func (mr *MockLinkServicerMockRecorder) GetSecret(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecret", reflect.TypeOf((*MockLinkServicer)(nil).GetSecret), name)
}

// GetShort mocks base method.
func (m *MockLinkServicer) GetShort(ctx context.Context, shortURL string) (model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShort", ctx, shortURL)
	ret0, _ := ret[0].(model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShort indicates an expected call of GetShort.
func (mr *MockLinkServicerMockRecorder) GetShort(ctx, shortURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShort", reflect.TypeOf((*MockLinkServicer)(nil).GetShort), ctx, shortURL)
}

// GetStats mocks base method.
func (m *MockLinkServicer) GetStats(ctx context.Context) (model.Stats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(model.Stats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockLinkServicerMockRecorder) GetStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockLinkServicer)(nil).GetStats), ctx)
}

// MarkAsDeleted mocks base method.
func (m *MockLinkServicer) MarkAsDeleted(ctx context.Context, userID model.UserID, shortLinks model.ShortUrls) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsDeleted", ctx, userID, shortLinks)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsDeleted indicates an expected call of MarkAsDeleted.
func (mr *MockLinkServicerMockRecorder) MarkAsDeleted(ctx, userID, shortLinks interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsDeleted", reflect.TypeOf((*MockLinkServicer)(nil).MarkAsDeleted), ctx, userID, shortLinks)
}

// PingDB mocks base method.
func (m *MockLinkServicer) PingDB(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingDB", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingDB indicates an expected call of PingDB.
func (mr *MockLinkServicerMockRecorder) PingDB(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingDB", reflect.TypeOf((*MockLinkServicer)(nil).PingDB), ctx)
}

// ProvideUserLinks mocks base method.
func (m *MockLinkServicer) ProvideUserLinks(ctx context.Context, userID model.UserID) ([]model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvideUserLinks", ctx, userID)
	ret0, _ := ret[0].([]model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvideUserLinks indicates an expected call of ProvideUserLinks.
func (mr *MockLinkServicerMockRecorder) ProvideUserLinks(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvideUserLinks", reflect.TypeOf((*MockLinkServicer)(nil).ProvideUserLinks), ctx, userID)
}

// RegisterLinks mocks base method.
func (m *MockLinkServicer) RegisterLinks(ctx context.Context, longURLs []string, userID model.UserID) ([]model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterLinks", ctx, longURLs, userID)
	ret0, _ := ret[0].([]model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterLinks indicates an expected call of RegisterLinks.
func (mr *MockLinkServicerMockRecorder) RegisterLinks(ctx, longURLs, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterLinks", reflect.TypeOf((*MockLinkServicer)(nil).RegisterLinks), ctx, longURLs, userID)
}
