// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Pklerik/urlshortener/internal/repository (interfaces: LinksStorager)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "github.com/Pklerik/urlshortener/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockLinksStorager is a mock of LinksStorager interface.
type MockLinksStorager struct {
	ctrl     *gomock.Controller
	recorder *MockLinksStoragerMockRecorder
}

// MockLinksStoragerMockRecorder is the mock recorder for MockLinksStorager.
type MockLinksStoragerMockRecorder struct {
	mock *MockLinksStorager
}

// NewMockLinksStorager creates a new mock instance.
func NewMockLinksStorager(ctrl *gomock.Controller) *MockLinksStorager {
	mock := &MockLinksStorager{ctrl: ctrl}
	mock.recorder = &MockLinksStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinksStorager) EXPECT() *MockLinksStoragerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLinksStorager) Create(arg0 context.Context, arg1 model.LinkData) (model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLinksStoragerMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinksStorager)(nil).Create), arg0, arg1)
}

// FindShort mocks base method.
func (m *MockLinksStorager) FindShort(arg0 context.Context, arg1 string) (model.LinkData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShort", arg0, arg1)
	ret0, _ := ret[0].(model.LinkData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShort indicates an expected call of FindShort.
func (mr *MockLinksStoragerMockRecorder) FindShort(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShort", reflect.TypeOf((*MockLinksStorager)(nil).FindShort), arg0, arg1)
}
